language: objective-c

before_install:
  - brew update
  - brew remove xctool
  - brew install xctool

notifications:
  webhooks:
    - http://staging.ironbroker.flatironschool.com/e/travis/build
    - http://staging.ironbroker.flatironschool.com/e/travis/build/dan-staging
    - http://46809191.ngrok.com/e/travis/build/dan-dev


script: xctool -reporter json-stream -workspace objc-deli/Objc-deli.xcworkspace -sdk iphonesimulator7.1 -scheme Objc-deli build test
