language: objective-c

before_install: 
  - brew update
  - brew remove xctool
  - brew install xctool
  
notifications:
  webhooks:
    - http://staging.ironbroker.flatironschool.com/e/github/push/lab_update
    - http://staging.ironbroker.flatironschool.com/e/travis/build

script: xctool -reporter json-stream -workspace objc-deli/Objc-deli.xcodeproj -sdk iphonesimulator7.0 -scheme Objc-deli build test
