language: objective-c

before_install:
  - brew update
  - brew remove xctool
  - brew install xctool

notifications:
  webhooks:


script: xctool -reporter json-stream -workspace objc-deli/Objc-deli.xcworkspace -sdk iphonesimulator7.1 -scheme Objc-deli build test
